import { fileURLToPath } from "node:url";
/**
 * Generates scripts/generated/assets.ts — the embedded-asset manifest used by
 * `bun build --compile` (driven by scripts/build-binary.sh).
 *
 * Every dist/ file is imported `with { type: "file" }`, which makes the Bun
 * compiler embed the file's bytes into the executable and hand the module a
 * file:// URL into the binary's virtual FS. scripts/embed-shim.ts maps the
 * server's "/$bunfs/dist/..." lookups onto those URLs, so a compiled binary
 * serves the frontend with no adjacent dist/ folder.
 *
 * Run automatically by scripts/build-binary.sh (which builds dist/ first).
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(repoRoot, "dist");
const outDir = join(repoRoot, "scripts", "generated");
const outFile = join(outDir, "assets.ts");

if (!existsSync(join(distDir, "index.html"))) {
  console.error(
    "[embed-dist] dist/index.html not found — run `bun run build` first (scripts/build-binary.sh does this automatically).",
  );
  process.exit(1);
}

const files: string[] = [];
(function walk(dir: string) {
  const entries = readdirSync(dir, { withFileTypes: true });
  entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
})(distDir);

const toDistPath = (full: string) => "/" + relative(distDir, full).split("\\").join("/");

const lines: string[] = [
  "// @ts-nocheck — GENERATED by scripts/embed-dist.ts; do not edit or commit.",
  "// Imports every dist/ file (plus the agent skill) with { type: \"file\" } so",
  "// `bun build --compile` embeds the frontend bytes into the executable.",
  "// Regenerated by scripts/build-binary.sh on every run.",
  "",
];
files.forEach((full, i) => {
  const rel = relative(distDir, full).split("\\").join("/");
  lines.push(`import f${i} from "../../dist/${rel}" with { type: "file" };`);
});
// The agent skill rides along so compiled binaries can still sync it to
// ~/.config/opencode/skills/webui/ (node:fs cannot read the binary's virtual FS).
const hasSkill = existsSync(join(repoRoot, "skills", "webui", "SKILL.md"));
if (hasSkill) lines.push(`import skill from "../../skills/webui/SKILL.md" with { type: "file" };`);
lines.push("");
lines.push("/** dist-relative path (\"/index.html\") -> embedded asset URL inside the binary. */");
lines.push("export const embeddedDist: Record<string, string> = {");
for (const [i, full] of files.entries()) {
  lines.push(`  ${JSON.stringify(toDistPath(full))}: f${i},`);
}
lines.push("};");
lines.push("");
lines.push("/** Embedded copy of skills/webui/SKILL.md, or null when it was missing at build time. */");
lines.push(`export const embeddedSkill: string | null = ${hasSkill ? "skill" : "null"};`);
lines.push("");

const content = lines.join("\n");
mkdirSync(outDir, { recursive: true });
const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
if (prev !== content) writeFileSync(outFile, content);
console.log(`[embed-dist] embedded manifest: ${files.length} dist files -> ${relative(repoRoot, outFile)}`);
