/**
 * Compiled-binary asset shim — imported by scripts/compile-entry.ts BEFORE
 * server/index.ts, so the patch below is in place before the server's static
 * handler runs. Never imported by dev/npm entrypoints.
 *
 * Why this exists: inside a `bun build --compile` executable every module's
 * import.meta.url is a virtual path (file:///$bunfs/root/<bin>), so
 * server/index.ts computes DIST_DIR = "/$bunfs/dist/" — a location that only
 * exists when dist/ files are EMBEDDED in the binary (an adjacent dist/ folder
 * is never consulted). scripts/embed-dist.ts generates a manifest that embeds
 * every dist/ file via `with { type: "file" }`; this shim patches Bun.file so
 * the server's `Bun.file(DIST_DIR + ...)` lookups resolve to those embedded
 * copies. Nothing else changes, and the "/$bunfs/dist/" prefix can never occur
 * outside a compiled executable — dev and npm paths are untouched.
 */
// @ts-ignore — scripts/generated/assets.ts is GENERATED by scripts/embed-dist.ts
// (build-binary.sh runs it before compiling); it does not exist on a fresh
// checkout, and this import must stay error-free in either state.
import { embeddedDist, embeddedSkill } from "./generated/assets";

const BUNFS_DIST = "/$bunfs/dist/";
const BUNFS_SKILL = "/$bunfs/skills/webui/SKILL.md";
const realFile = Bun.file.bind(Bun);

// A compiled binary is always production. server/index.ts gates the static
// branch on Bun.env.NODE_ENV, and compiled executables do NOT get NODE_ENV
// injected at runtime (`--compile` does not set it; Bun.env mirrors the launch
// environment, where it is usually unset). The assignment goes through a
// computed key ON PURPOSE: `--production` inlines/deletes plain
// `process.env.NODE_ENV = ...` writes at build time (verified on Bun 1.3.14 —
// the statement vanishes from the bundle), while this shape survives and the
// write propagates to the live environment at boot.
(process.env as Record<string, string | undefined>)["NODE_ENV"] = "production";

(Bun as { file: unknown }).file = (input: string | URL) => {
  // fileURLToPath (used by the server on win32) produces backslash paths even
  // for the virtual /$bunfs locations — normalize before matching.
  const raw = typeof input === "string" ? input : input.pathname;
  const path = raw.replace(/\\/g, "/");
  if (path.startsWith(BUNFS_DIST)) {
    const hit = embeddedDist["/" + path.slice(BUNFS_DIST.length)];
    if (hit) return realFile(hit);
  }
  if (embeddedSkill && path === BUNFS_SKILL) return realFile(embeddedSkill);
  return realFile(input);
};
